### ISSUE TITLE
Request for dump data

### ISSUE THREAD

**Issue by caravagn** [albertocasagrande/RACES#5]
Precise specs for simulation dumps (for the wrappers):

- [ ] _bulk mutation data_: for every time-point or tissue sample, potentially split by `+`/`-` status. Whatever the scenario, counts data need to be reported for all simulated mutations, even for the samples where they are missing. I would use a tabular format.
- [ ] _single-cell genotypes:_ like _bulk mutation data_, but this time we report the true single-cell genotypes.
- [ ] _tumour population statistics over time_: the total per species every `k` steps of the simulation (e.g., every 1 time-unit)
- [ ] _tumour spatial configuration over time_: the position of every simulated cell (with their species id, and `+`/`-` status), every `k` steps of the simulation (e.g., every 1 time-unit)
- [ ] _tumour spatial configuration at sampling_: like the _tumour spatial configuration over time_, but this time only at sampling, i.e.,  whenever a _mutation data_ is generated. This should report also the bounding boxes of the simulated sampling.

**Comment by albertocasagrande** [comment]
Can you be more specific and describe the columns of the tabular that you expect to get about _bulk/single-cell mutation data_?

**Comment by caravagn** [comment]
The bulk we have now seems a good to begin with.

For the single-cell we have two options, and both could be interesting:

### _Genotype view_

```
chr    from     to  ref    alt    cell_id  
```
reporting the presence of mutation at the usual coordinates, in cell `cell_id`.

### _single-cell read counts data_

Like the bulk file (so read counts per cell), but split per single cell. 

**Note** I am thinking of this because you told me that you generate reads from single-cells, and then you pile them up to simulated a bulk sample. Therefore, I am assuming that if the bulk sample reports some values of `DP`/`NV` those are just the total sum over all read counts of the sequenced cells.
