### ISSUE TITLE
Cell tree phylogeny format

### ISSUE THREAD

**Issue by caravagn** [albertocasagrande/RACES#7]
**Format** In the `phyloXML` format we need to specifiy the following fields:

- `species` with a name for the species the cell belongs to;
- `epi-state` with a `+`/`-` value
-  `sampling` if we intend to dump a uinque phylogenetic tree for a simulation with multiple samples collected over time and space, we need a unique code that tells us when and where the cell has been sampled.

That is all we need to identify cell states.

**Branch length**

I still need to understand though if our current tree is actually modelling branch length as standard in phylogenies  -- I suspect no.

Right now I believe that the dots are past cell division events, so branch length models the number of divisions. Instead, in a phylogeny, the length of each branch should report the number of mutations that have accumulated.

It would be best to have both info in our model:

- cell division events  + internal cell states, so we know past states of cells etc
- a distance of `n` if there have been `n` mutations accumulated between the cell `i` to `i+1` (in a single-division)

**Comment by albertocasagrande** [comment]
Unfortunately, the standard `phyloXML` does not appear to support extensions. Hence, we can add tags, but none but our tools will be able to deal with them. 

The proposed `sampling` tag is only meaningful in the phylogenetic tree leaves. 

About the branch length: at the moment, the phylogenetic tree is produced before the mutation simulation. Each dot represents a cell birth, and the length of an edge depicts the cell life span. An edge connects two cells if they are in parent/child relation. 
If we want a tree whose branch lengths depend on the number of mutations, we must simulate the mutations first and then produce the tree. 

Why do we need all these pieces of information about the tree? Do we want to plot it? Do we need to pass the tree to another tool? In the former case, we do not need to export all these pieces of information in XML to reload them and plot the tree.

**Comment by caravagn** [comment]
> Unfortunately, the standard `phyloXML` does not appear to support extensions. Hence, we can add tags, but none but our tools will be able to deal with them.

It is OK if we add tags that our wrapper tools can interpret. In the same way now you have added the colour scheme, we can add any tag that is important for other tools to plot.

> 
> The proposed `sampling` tag is only meaningful in the phylogenetic tree leaves.

Yes, of course.

> About the branch length: at the moment, the phylogenetic tree is produced before the mutation simulation. Each dot represents a cell birth, and the length of an edge depicts the cell life span. An edge connects two cells if they are in parent/child relation. If we want a tree whose branch lengths depend on the number of mutations, we must simulate the mutations first and then produce the tree.

I understand, and in fact what we plot now is the tree of cell divisions, not a cell phylogeny. Both are useful, but a phylogeny by definition always reports the number of mutations among species as branch length. 
 
> Why do we need all these pieces of information about the tree? Do we want to plot it? Do we need to pass the tree to another tool? In the former case, we do not need to export all these pieces of information in XML to reload them and plot the tree.

We generally need all these pieces of information because we want to take sequencing data (bulk/single-cell etc) to make inferences about the process. Essentially we want to infer stats from this tree, which is the reason need to dump all this data to disk for wrapper tools to load them (post hoc), and compute statistics.

An example of what one might want to do is: https://en.wikipedia.org/wiki/Coalescent_theory

**Comment by albertocasagrande** [comment]
> I understand, and in fact what we plot now is the tree of cell divisions, not a cell phylogeny. Both are useful, but a phylogeny by definition always reports the number of mutations among species as branch length.

So let us produce two different trees.

> We generally need all these pieces of information because we want to take sequencing data (bulk/single-cell etc) to make inferences about the process. Essentially we want to infer stats from this tree, which is the reason need to dump all this data to disk for wrapper tools to load them (post hoc), and compute statistics.

My point was: "Do we really need to reverse all these pieces of information in an XML file or provide API to get them directly from the RACES structures?" What if our tree nodes store the cell ids and we have a function `species(cell_id)`?

**Comment by caravagn** [comment]
Sure that is a possibility. I think that if we go for the API approach then all these things will become APIs.
