### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by caravagn** [albertocasagrande/RACES#9]
It is handy that it shows

```
 [███████████████████████████████████████-] 97% [01m:40s] Cells: 987224
```

but it could also report the current `clock`.

**Comment by albertocasagrande** [comment]
The progress bar reports the percentage of the goal, i.e., when a `TimeTest` is used as the first parameter for `Simulation::run(...)`, the bar reports the percentage of the simulated time over the aimed simulation time; when a `SpeciesCountTest` is used, the bar reports the percentage of the number of cells in the species over the aimed number of cells; etc.
